/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CitiesList: typeof import('./../components/main-page/CitiesList.vue')['default']
    City: typeof import('./../pages/city.vue')['default']
    Pages: typeof import('./../pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/main-page/SearchForm.vue')['default']
    UiInput: typeof import('./../components/ui/UiInput.vue')['default']
    UiNotification: typeof import('./../components/ui/UiNotification.vue')['default']
    WeatherByDay: typeof import('./../components/weather/WeatherByDay.vue')['default']
    WeatherHeader: typeof import('./../components/weather/WeatherHeader.vue')['default']
    WeatherTodayByHour: typeof import('./../components/weather/WeatherTodayByHour.vue')['default']
    WeatherTodayCard: typeof import('./../components/weather/WeatherTodayCard.vue')['default']
  }
}
